# Generated by Django 5.2 on 2025-05-05 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidates',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Rural', 'Rural Municipality'), ('Urban', 'Urban Municipality'), ('SubMetropolitan', 'Sub-Metropolitan City'), ('Metropolitan', 'Metropolitan City')], max_length=20)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='api.district')),
            ],
            options={
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.province'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_no', models.PositiveIntegerField()),
                ('info', models.TextField(blank=True, null=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='api.municipality')),
            ],
            options={
                'unique_together': {('ward_no', 'municipality')},
            },
        ),
        migrations.AddField(
            model_name='candidates',
            name='ward',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='api.ward'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='candidates',
            unique_together={('post', 'ward')},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'province')},
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='address',
        ),
    ]
