# Generated by Django 5.2 on 2025-05-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ward_unique_together_candidates_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='ward_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('ward_no','municipality')},
        ),
        
        migrations.RemoveField(
            model_name='ward',
            name='ward_numbers',
        ),
    ]
