# Generated by Django 5.2 on 2025-05-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ward_unique_together_ward_ward_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='post',
            field=models.CharField(choices=[('Chairperson', 'chairperson'), ('Vice-Chairperson', 'vice-chairperson'), ('Secratary', 'secratary'), ('Member', 'member')], max_length=50),
        ),
    ]
