# Generated by Django 5.2 on 2025-05-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_country_user_date_of_birth_user_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
